version: '3.8'

services:
  banco_db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - development

  banco_proyectos_web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn projectbank.wsgi:application --bind 0.0.0.0:8081"
    volumes:
      - .:/app
      - ./banco_staticfiles:/staticfiles
#      - ./media:/media/banco_proyectos
    networks:
      - development
    depends_on:
      - banco_db
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=projectbank.settings.dev
    ports:
      - "8081:8081"

volumes:
  postgres_data:

networks:
  development:
    external: true
